### ISSUE TITLE
Invalid SigningKey Blob Format

### ISSUE THREAD

**Issue by marcusnewton** [holochain/holoscape#52]
For all version of Holoscape I get this error when unlocking keystore.

```
Error while trying to boot from config: ConfigError("Could not decrypt \'primary_keybundle:sign_key\': ErrorGeneric(\"Invalid SigningKey Blob Format: v0 != v1\")")

holochain process terminated with exit code 0
```

**Comment by Connoropolous** [comment]
Hi @marcusnewton ...
I know it's been a while, but just curious, you got over this issue right?

**Comment by marcusnewton** [comment]
@Connoropolous if I recall correctly, I believe the problem had something to do with first installing the second application in the list (which I think was the Chat app), rather than the first application (Hylo communities).

The Hylo communities app seemed to set up the keystore correctly when it was run before the other apps.

**Comment by Connoropolous** [comment]
Interesting. 
In general, I would think that the problem was having a version (v0) of the Keystore encryption algorithm, and a new version of Holochain needing the new one. Requiring you to clear old key files, and start fresh. With Holoscape, the config files can be accessed from here:

<img width="459" alt="Screen Shot 2020-02-25 at 4 51 30 PM" src="https://user-images.githubusercontent.com/1409121/75290840-1b987d00-57ef-11ea-9054-a20c5bbcb2eb.png">

Leaving this as breadcrumbs for future strugglers, in the meantime, I'm thinking we can close this issue?

**Comment by marcusnewton** [comment]
That would make sense. Closing
